import React from 'react';
import { Switch, Route } from 'react-router-dom';

function VOY_S4_Episodes() {
  return (
    <Switch>
      <Route path="/VOY/S4/1" render={() => (<span>
Janeway and Tuvok work with the Borg and meet Seven of Nine as they
collaborate on developing a weapon against Species 8472 in exchange for
safe passage through Borg space.
      </span>)} />
      <Route path="/VOY/S4/2" render={() => (<span>
Kes' mental abilities develop to a point where they endanger Voyager.
      </span>)} />
      <Route path="/VOY/S4/3" render={() => (<span>
B'Elanna tries to observe the Klingon Day of Honor after the warp core is lost.
      </span>)} />
      <Route path="/VOY/S4/4" render={() => (<span>
Chakotay helps fight in an alien war.
      </span>)} />
      <Route path="/VOY/S4/5" render={() => (<span>
A hologram contacts Voyager and the Doctor is excited to meet another hologram.
      </span>)} />
      <Route path="/VOY/S4/6" render={() => (<span>
Seven of Nine experiences Borg flashbacks as she attempts to become more human.
      </span>)} />
      <Route path="/VOY/S4/7" render={() => (<span>
The crew have unexplained illnesses as they are closely observed by unseen
intruders.
      </span>)} />
      <Route path="/VOY/S4/8" render={() => (<span>
Voyager creates a new Astrometrics lab, which maps a new course that brings
them into contact with a Krenim temporal ship that can erase things from history.
      </span>)} />
      <Route path="/VOY/S4/9" render={() => (<span>
A badly damaged Voyager hides in a nebula as a skeleton crew attempts
repairs; meanwhile the Krenim commander proposes a compromise to
Chakotay and Tom Paris.
      </span>)} />
      <Route path="/VOY/S4/10" render={() => (<span>
Torres is arrested while visiting a world of telepaths where violent
thoughts are a crime.
      </span>)} />
      <Route path="/VOY/S4/11" render={() => (<span>
Aliens steal several key components of Voyager, which are retrieved with
assistance from a holographic Leonardo da Vinci.
      </span>)} />
      <Route path="/VOY/S4/12" render={() => (<span>
Neelix dies in an attempt to sample proto-matter from a nebula.
Seven of Nine helps resuscitate him using Borg nanoprobes, but Neelix,
having no memory of an afterlife of any kind, experiences a spiritual crisis.
      </span>)} />
      <Route path="/VOY/S4/13" render={() => (<span>
The crew become trapped in a shared nightmare generated by alien technology.
Only Chakotay, through his Native American spiritual capabilities, can save them.
      </span>)} />
      <Route path="/VOY/S4/14" render={() => (<span>
The Doctor's program is sent to an advanced Starfleet vessel via a vast
ancient communications network, but he soon discovers that only he and the
ship's own EMH remain to fight against Romulans who have taken over the ship
and are attempting to return to Romulan space with it.
      </span>)} />
      <Route path="/VOY/S4/15" render={() => (<span>
A transmission from Starfleet Command gets held at a Hirogen relay station
and Janeway sets course to retrieve it.
      </span>)} />
      <Route path="/VOY/S4/16" render={() => (<span>
Voyager rescues a Hirogen survivor who tells them a new kind of prey is on the
loose.
      </span>)} />
      <Route path="/VOY/S4/17" render={() => (<span>
After experiencing unsettling hallucinations, Seven of Nine is hypnotized by
the Doctor whose analysis reveals a trader may have extracted Borg technology
from Seven without her consent.
      </span>)} />
      <Route path="/VOY/S4/18" render={() => (<span>
The Hirogen implant devices into the crew making them believe they are
characters within the holodecks being used for hunts, all set in World War II
Europe.
      </span>)} />
      <Route path="/VOY/S4/20" render={() => (<span>
An alien shuttle with a prototype propulsion system suddenly appears and
requires assistance. Paris is restless and volunteers to help the pilot,
Steth, repair the shuttle.
      </span>)} />
      <Route path="/VOY/S4/21" render={() => (<span>
Janeway undertakes the Omega Directive, an order to destroy Omega molecules,
even if it means violating the Prime Directive.
      </span>)} />
      <Route path="/VOY/S4/22" render={() => (<span>
An alien female from a cloaked ship asks for Chakotay by name and
requests asylum on Voyager from her people.
      </span>)} />
      <Route path="/VOY/S4/23" render={() => (<span>
A Kyrian museum curator 700 years in the future hopes a Voyager relic
containing a copy of the Doctor can confirm their version of history.
      </span>)} />
      <Route path="/VOY/S4/24" render={() => (<span>
Tom Paris and Harry Kim take a shuttle down to an extremely inhospitable
planet to obtain fuel.
      </span>)} />
      <Route path="/VOY/S4/25" render={() => (<span>
Seven of Nine is left alone on Voyager when a nebula's deadly radiation
forces the rest of the crew to stay in stasis and the Doctor's hologram
projectors are disrupted.
      </span>)} />
      <Route path="/VOY/S4/26" render={() => (<span>
Paris and Neelix return from a mission with a passenger named Arturis who
knows more than 4,000 languages. He manages to decode a message from
Starfleet that could lead to a way home.
      </span>)} />
    </Switch>
  );
}

export default VOY_S4_Episodes;